### ISSUE TITLE
서비스 아이디어 생각하기

### ISSUE THREAD

**Issue by junsubenkim** [Yapp-17th/iOS_1_Client#2]
개발할 서비스 선정을 위해, 먼저 **최대한 많은 아이디어**를 뽑아내 봅시다.
각자 **아이디어 최소 1개씩** 생각해서 공유해 주세요. 많으면 많을수록 좋아요.
아이디어 단계이니만큼 **주기능은 최대한 심플하게** 생각해주세요. **부연 설명은 구체적**일수록 좋습니다.
(ex. 생각하게 된 이유, 타겟 사용자, 니즈, 차별점 등등)

**Due date : 8월 5일 수요일 밤 11:59까지**

**Comment by junsubenkim** [comment]
### **아이디어 1. 연락처 정리 어플**
"연락 안 한 지 몇 년 넘었는데 몇백 개씩 자꾸 쌓여만 가는 연락처, 손쉽게 정리할 수는 없을까?"
일정 기간동안 연락(왕래) 없었던 연락처 sort해서 보여주고 삭제/정리할 수 있는 어플

### **아이디어 2. 어플 정리 어플**
"이 어플 안 쓴지 얼마나 됐더라..?"
어플 별로 마지막 사용 날짜를 보여주고, 일정 기간동안 사용 안했던 어플 sort해서 보여줌.
sort된 결과를 바탕으로 한 번에 많은 어플을 삭제/정리할 수 있는 어플

**Comment by adfilm2** [comment]
1. 봉사활동 어플
근처에 자원봉사자가 필요한 시설이나 단체를 한눈에 파악하고 검색할 수 있음. +)봉사시간 예약
2. 페이지 저장어플
나중에 봐야지 했던 링크들 보기 좋게 모아볼 수 있는 어플
카테고리로 분류 가능, 까먹지 않게 푸쉬알람 설정 가능

**Comment by ujusy** [comment]
**1. 자취생 주변 식당(or 식사 메뉴) 추천 어플 **
-  슥삭이라는 어플에서 영감을 얻음. 
-  자취를 하면서 하루 점식, 저녁 메뉴를 많이 고민하게됨
- 슥삭이라는 어플을 보면 공모전 활동이나 대외활동 등을 슥 넘기는 방식으로 하는데 메뉴 추천을 그렇게 해도 좋을 것 같다.

**2. 주변 카페 음료 가격 비교**
- 회사 다니면서 떠오른 생각
- 아메리카노를 마시고 싶은데.. 저렴하게 마시고 싶지만 어디에 카페가 있는지 모르겠음
- 거리와 가격 비교 해주는 어플

**Comment by hjoopark** [comment]
1. 목표를 달성 시켜주는 어플
- 목표를 설정하고 공부나 운동 등을 시작하면 좀 더 달성하기 쉬움
- 시험을 앞둔 사람들이나 다이어터가 사용하기 좋음
- '두잇노트'라는 어플을 참고하면 좋을 것 같다.

**Comment by suath** [comment]
1. 주량체크 : 내 술자리 메이트!

"대한민국 직장인 평균 주 2회 술자리, 귀가시간 9-12pm"

아이디어는 기분전환앱과 결이 같은데, 다른 점이라면 우울>밝음에서 멀쩡>취함으로, 또한 술자리라는 시간으로 한정시킨다는 정도? 굳이 많은걸 포괄하지 않고도 사용자가 자발적으로 on/off를 할 수 있다는 점에서 관리가 쉬울것같아요. 

술자리에서 일어나야 할 시간과 취함 정도를 알려주는 어플이 있었으면 좋겠다는 생각을 했습니다. 내 주량과 막차 시간을 입력, 잘 마시고 있는지 오버하진 않고 있는지 푸시로 점검하는거죠! 그 다음날엔 내 술자리를 평가해서 주의를 주거나 응원해주고요. 

크리티컬한 기능은 막차시간 혹은 술자리 끝날 시간 점검, 푸쉬가 될것같고, 내 주량 트래킹이나 술자리 트래킹 같은 것들이 부가기능이 될거같아요. 공유를 해서 믿을 만한 사람에겐 오픈하여 술자리 챙김동지를 만들수도 있고요. 시장조사를 해봐야겠지만 이런 앱을 쓰는 사람이 없어서, 적어도 저에게는 도움이 많이 될 것 같습니다 ㅎㅎ 

2. 랩퍼되보기 : 랩 가사쓰기와 비트제공 내일은 나도 힙합퍼! 연습

16마디 랩을 써가는데 있어, 한국말로 라임이 얼마나 맞는지 체킹, 완성된 랩은 메트로놈과 함께 노래방처럼 불러볼 수 있으면 어떨까. 비트 제공은 못해줄것 같고, 영문이라면 알파벳 대 훈민정음이 얼마나 호환되는지 우리가 직접 데이터를 만들면 사용자 입력 데이터가 첫문장과 뒷문장이 얼마나 유효한지 따질수도 있을것 같다는 생각이 들었어요. 그래서 랩 초심자라면 시키는 대로만 가사를 써보면, 라임이 잘 맞는 가사를 써볼 수 있다! ㅋㅋㅋ

**Comment by escapeanaemia** [comment]
## 대학생 방학 숙제 / 직장인 방학 숙제
-  초등학교때 방학숙제를 했던것 처럼, 방학숙제를 내주고 이를 잘 완료할 수 있도록 해주는 서비스
- 자신의 전공이나 원하는 취업 분야, 학년 등의 정보를 입력하면 해당 정보를 토대로 맞춤형 (방학)숙제를 제공해줌.
- 취지 - 방학에도 생산적으로 하루를 살아가고 싶은 사람들에게 방학숙제(자기개발)를 통해 성취감을 느낄 수 하도록
- 직장인들이 자기개발의 목적으로 눈높히 중국어 같은걸 많이 수강한다는 기사를 보고 아이디어를 얻었어용 ㅎㅎ

## 얼리버드
- 아침 일찍 기상하고 싶은 사람들을 위한 서비스
- 핸드폰 사용시간을 추적하여 수면 시간을 유추한 후 아침일찍 일어나고 저녁늦게 자지 않으면 적절한 보상을 줌
- tmi - 올빼미 생활 그만하고 싶습니다 ㅠㅠ

## 마스크필터
- 마스크를 쓰고 사진을 찍으면 마스크를 인식하고 해당 마스크를 이쁘게 꾸며주는 서비스

**Comment by junsubenkim** [comment]
<첫 세션(8/1)에서 나왔던 아이디어들>

1안 : 미션 기반 기분전환 앱
- 매일 기분 물어보기 -> 기분에 따른 기분전환할 수 있는 미션 부여 (by 푸시알림) -> 자기 전에 감정상태 체크

2안 : 미션 기반 습관형성/생활태도 바꾸기 (일명 '백수탈출' 앱)
- 자신의 삶 진단 (ex. 하루에 잠을 몇시간 잔다, 운동/게임/유튜브 등을 몇시간 한다) 후 상태 파악 -> 생활 태도 개선할 수 있는 습관 형성을 미션 형식으로 도와주기 (by 푸시알림)

3안 : e스포츠(LCK) 응원팀 정보 앱
- 프로야구 응원팀 정보앱인 'PAIGE' 벤치마킹해서 e스포츠(LCK)에 적용
- 경기 일정, 경기 영상/하이라이트, 경기 기록, 팀순위/선수순위, 팀 뉴스 등등 제공

4안 : Lo-fi 음악 변환 앱
- 사용자가 가지고 있는 음악 파일을 Lo-fi 버전으로 바꿔주는 서비스
