### ISSUE TITLE
데스크 리서치 / 잠재사용자 설문조사

### ISSUE THREAD

**Issue by junsubenkim** [Yapp-17th/iOS_1_Client#4]
세 개 아이디어 각각에 대한 데스크 리서치와 잠재사용자 대상 설문조사를 진행합니다. 이를 통해 각각의 아이디어가 소비자에게 얼마나 설득력이 있는지 파악합니다.

**Comment by junsubenkim** [comment]
- **백수탈출 앱 질문지**
https://docs.google.com/document/d/15ArEkN_EwBj8eU3Pu4D0FFqfgHkS7_gMMbsl7EAtK28/edit?usp=sharing

- **e스포츠 앱 질문지**
https://docs.google.com/document/d/1w8-lUQ60Lh5Z8DLcj9Laivoc1InI6HuyKvt9R9jZ7RA/edit?usp=sharing

- **카페 앱 질문지**
https://docs.google.com/document/d/1RybW3oXdmR0SML9dJ78S-wGQqizWSdSnnjiwBXidgKk/edit?usp=sharing


질문지 검토해 보시고, 피드백을 코멘트로 남겨 주시고 자유롭게 편집해 주세요!

**Comment by junsubenkim** [comment]
https://drive.google.com/drive/folders/1SBSVR_h8jDSuZ8uwztNcXi9sVfmoYK9D?usp=sharing

남겨주신 코멘트를 반영해서 질문지를 구글 폼으로 만들었습니다. 확인해 주세요.

**Comment by ujusy** [comment]
### **백수 탈출 앱**
--------
분석할 당시 백수 탈출 앱은 총 58개의 응답을 기록했다.

**분석 및 중요하다고 느끼는 포인트**
-  게으르다고 느낄 때는 대부분이 낮잠이라고 작성하였다.
- 게을러진 이유의 응답
>  1. 아무것도 하지 않고 싶다. 54.5%
>  2. 늦게 일어났다. 43.6%
>  3. 뚜렷한 목표가 없었다. 40%
- 나태한 생활을 긍복한 노력을 살펴보면 알바, 자격증 접수, 스터디 , 계획짜보기,운동 등 종합해보면 결과적으로 목표를 두고 성취해 나가는 방식이 주를 이루고 있음을 확인할 수 있다.
- 백수 탈출 앱이 존재한다면 한 번 써보기는 할 거 같다는 반응이 주를 이루었다.

**시사점 및 느낀점**
-  사용자가 처음 시작은 가볍게 사용할 수 있게 해주어 거부감을 느끼지 않게 그리고 귀찮지 않게 해주는 것이 중요할거 같다는 생각이 들었다.
-  한 번 써보기는 할거 같다는 반응이 주를 이룬 만큼 꾸준한 사용을 위해 그만한 효과를 제공하거나 혹은 즐거움을 제공하여 꾸준한 사용을 장려하는 것이 좋다고 본다.


### **카페 가격 비교 앱**
--------
분석할 당시 카페 가격 비교 앱은 43회의 응답을 기록했다.

**분석 및 중요하다고 느끼는 포인트**
- 응답을 기록한 사람중 90.7 퍼센트의 사람이 일주일에 1회 이상의 커피를 마셨다.
- 4회 이상 마시는 사람들은 총 62.8 퍼센트를 기록하였다.
- 일반적인 경우 대부분의 사람들은 커피를 마실 때 ```접근성```을 일순위로, 이 순위로는 ```가격```을 삼 순위로는 `가격과 접근성`이 동등한 비율을 가졌다. 
- 처음 가보는 지역일 경우 `접근성` 이 압도적인 일위를 가졌으며 가격과 커피맛이 그 아래 순위를 차례로 기록했다.
- 이러한 어플이 존재할 경우 자주 사용할 것 같다와 한 번 써보기는 할거같다는 응답이 동일한 비율을 이루었다.
- 필요하다고 느기는 서비스는 자리 유무에 대한 내용이 주를 이루었고 메뉴와 가격이 정확하며 후기에 대한 응답이 많았다.

**시사점 및 느낀점**
- 이 앱의 주목적을 생각해보면 다른 사람을 만나 놀러가서 얘기할 때 카페를 찾는 용도로는 알맞지 않은거같다 ( 이 때 인테리어가 압도적인 일위를 기록함)
- 주로 자리 유무를 확인할 수 있었으면 좋겠다라는 의견이 많았는데 이는 전산 처리가 안되어서 힘들거 같다.
- 만약 한다면 지역별 혹은 동 별로 자리 커뮤니티를 만들어서 사용자끼리 공유하는 방법인데 이는 많은 사용자가 있어야 가능할 것이라고 예상된다.
- 24시간 카페를 찾아주는 것도 있으면 좋을거 같다는 의견이 있었는데 수용가능할 것 같다.

### **e 스포츠 앱**
--------
분석할 당시 e스포츠 앱은 24회의 응답을 기록했다.

**분석 및 중요하다고 느끼는 포인트**
- e스포츠 경기를 즐겨보는 질문에 예와 아니오가 거의 5:5의 비율을 이루었다.
- 만약 e 스포츠 경기를 본다면 리그 오브 레전드가 압도적인 비율을 자랑했다.
-  결과에 관심을 갖고 꾸준히 확인하는 질문에는 확인하지 않는 사람을 제외하고(보지 않는 사람) 하루에 1회 이상 혹은 일주일에 1회 이상은 대부분 확인하였다.
-  이 때 결과를 확인하는 경로로 네이버 스포츠 앱과 웹이 압도적인 응답을 하였다.
- 필요한 서비스 응답에서는 알람기능과 가독성 등에 대한 응답이 많았다. (개개인 마다 응답이 매우 다양했다.)

**시사점 및 느낀점**
- 일단 주위 사람으로 설문조사를 하다보니 생각보다 e 스포츠에 관심이 있는 사람이 많지 않았다.
- 실제 수요가 많은 곳에서 진행한 설문이 아닌만큼 정보가 적었다고 생각한다.
- 대부분 게임에 대한 모든 지표를 볼때 가독성과 한눈에 들어오는지를 중요하게 생각했다고 생각한다.
- 개인적으로는 입문자들을 위한 팀 추천도 있었으면 좋겠다.

**Comment by junsubenkim** [comment]
### 백수탈출 앱

**1. 중요한 포인트**

- 응답자 직업 : **학생(27명, 39.7%), 대학생(19명, 27.9%)**으로 학생이 대부분
- 게을렀던 당시 하루 일과는 '늦잠', '**침대**에 누워 있기'가 많았다
- 게을러지게 된 이유 중 중요 포인트
> - 뚜렷한 목표가 없었다 : 26명 (41.9%)
> - 해야 할 일이 딱히 없었다 : 15명 (24.2%)
> - 무엇을 해야 할 지 몰랐다 : 14명 (22.6%)
> - 아무것도 하고 싶지 않았다 : 33명 (53.2%)
- 어떤 도움이 필요한가? 중 중요 포인트
> - 사소하고 간단한 목표/계획/할 일을 만들어 주는 것
> - 동기 부여
- 할 일을 계획하기는 했지만 잘 지키지 못한 경험 : '예'가 56명 **(88.9%)**
- ‘무엇을 해야 할 지 모르겠다’고 느꼈던 경험 : '예'가 42명 **(66.7%)**

**2. 시사점 및 느낀점**

- 학생들 중에서, 방학 or 휴학 기간동안 '자신이 나태하다'고 느끼는 경우가 유의미하게 많다. **'학생'과 '방학' 포인트에 집중**하면 니즈는 충분히 있을 듯
- **해야 할 일, 목표** 등이 **없거나 모르는** 경우가 많다
- 그들에게 필요한 것은
> - 침대에서 벗어나게 해 주기
> - 큰 목표가 아니라, **사소하고 간단한, 실현가능한 할 일**을 만들어 주는 것
> - (ex. 이불 개기, 세수하기, 밖에 한번이라도 나가기 등등)
> - 그리고 그것을 지킬 수 있게, 또 사소한 것부터 시작해서 자신을 바꿔나갈 수 있게 **동기부여**해 주는 것

### e스포츠 앱

**1. 중요한 포인트**
- 종목은 역시 **LoL**이 가장 많았다
- 경기 일정과 결과에 관심을 갖고 꾸준히 확인하는 사람들(15명) 중에는 **일주일에 1회 이상 확인하는 사람이 13명으로 빈도가 대체적으로 꽤 높은 편**이다. 하루에 1회 이상 확인하는 사람도 7명으로 꽤 많다
- 확인 경로는 **네이버 스포츠**가 대부분
- 불편함을 느꼈다는 경우는 생각 외로 **거의 없었다** (3명, 11.5%)
- 구체적 불편함은?
> - 일정 예고의 가독성
> - 여러 번의 클릭을 거쳐야 한다, 일일이 검색해야 한다
- 응원팀이 있는 응답자(16명) 중에서 하루에 1회 이상 팀의 경기일정과 결과 확인한다는 응답이 9명으로 절반 이상 차지
- 응원팀이 있는 응답자들 역시 네이버 스포츠를 가장 많이 이용하며, 특징적인 것은 해당 팀의 SNS도 많이 이용한다는 것(7명)
- 이 경우에도 불편함은 거의 없거나 위와 비슷함. **팀 SNS가 우리 팀의 정보만 선별적으로 확인하는 데 유용한 경로**로 사용되는 것으로 보임
- '본인이 좋아하거나 응원하는 팀을 위주로 경기 일정과 결과, 뉴스, 영상 등을 모아서 보여주는 어플리케이션이 있다면, 사용하실 의향이 얼마나 있으신가요?' 질문에 대한 답 중
'자주 사용할 것 같다'가 9명(56.3%)으로 가장 많음.

**2. 시사점 및 느낀점**
- 큰 불편함을 느끼는 유저는 생각보다 많이 없었다
- **응원팀 정보를 손쉽게 볼 수 있는 서비스에 대한 니즈는 있는 듯**
- **가독성과 간편함, 한 눈에 보기**가 중요한 포인트가 될 듯

### 카페 가격비교 앱

**1. 중요한 포인트**
- 평소 회사나 학교 다닐 때, 여러 곳을 돌아다니면서 이용하는 사람은 별로 없음
(6명, 13%)
- 평소 회사나 학교 다닐 때, 카페를 정하는 기준
> 1순위 : 접근성(19명)
> 2순위 : **가격(18명)**
> 3순위 : 가격(10명), 커피 맛(10명), 접근성(10명)
- 업무상(학업상) 이유로 처음 가 보는 지역에서 카페를 정하는 기준
> 1순위 : 접근성(25명)
> 2순위 : **가격(17명)**
> 3순위 : 커피 맛(19명)
- 사적인 이유로 처음 가 보는 지역에서 카페를 정하는 기준
> 1순위 : 인테리어(18명)
> 2순위 : 디저트 맛(11명)
> 3순위 : 가격(14명), 접근성(14명)
- 카페 찾는 경로
> SNS (31명, 67.4%)
> 포털 검색 (27명, 58.7%)
> 지도 서비스 (19명, 41.3%)
- 불편한 점
> SNS : 한 눈에 정보를 파악하기 어렵다, 정보의 신뢰성, 광고식 홍보
> 포털 : 리뷰의 신뢰성, 광고식 홍보, 가격과 영업시간 정보 부재
> 공통 : 자리가 없는 경우가 많다
- 필요한 것
> 남은 자리 수 알려주는 서비스
> 실제 이용객들의 솔직한 리뷰 서비스
> 메뉴와 가격에 대한 정확하고 상세하며 up-to-date한 정보

**2. 시사점 및 느낀점**
- **상황별로** 카페 찾는 기준이 확연히 **다르다**
업무상, 학업상 이유일 때는 가격과 접근성도 중요한 기준이 되지만, 사적 이유일 때는 그렇지 않다
- 남은 자리 수를 알고 싶어하는 니즈가 많이 보이는데, 이게 구현 가능할까? 안 되지 않을까... 물리적인 부분이 너무 많이 필요함
- 메뉴와 가격 정보에 대한 니즈보다도 '정확한 후기'에 대한 니즈가 더 많은 듯.
근데 리뷰 서비스는 이미 확보된 유저층이 필요한데... 힘들지 않을까
- 그럼 우리가 생각하는 '가격 중심으로 가까운 카페 비교해주기' 서비스는
**'업무상 또는 학업 상 이유로 처음 가보는 곳에서 카페를 찾으려는'** 사람들만 이용하게 될 텐데, 이런 상황 자체가 많은 사람들에게 자주 발생하는 것은 아니지 않을까... 그렇다면 여기에 대한 니즈가 크게 많이 있을까 하는 의문

**Comment by escapeanaemia** [comment]
## 백수탈출

### 시사점 혹은 느낀 점
- 게으르다고 느껴질 때 대부분 응답자의 하루 일과가 소비형 컨텐츠에 집중되어 있다(게임, 영상 시청.. 등)
- 생각보다 사람들이 잠을 많이 자서 놀랍다🤭
- 많은 사람들이 나태한 생활을 개선하려는 의지가(조금이라도) 있는거 같다. 그렇게 생각한 이유는 설문결과에서 생활을 개선하기 위해 아무 노력도 하지 않은 사람은 매우 드물었다
→ 서비스를 이용할 수 있는 확률이 조금이라도 있는 사람들이 생각보다 많아서 놀라움!

### 특기할 만한 포인트
- 계획을 잘 지키지 못한 경험이 잇는 사람의 비중이 매우 높다
- ‘무엇을 해야 할 지 모르겠다’고 느꼈던 경험이 있는 사람의 비중 역시 매우 높다.
- 생각보다 아무것도 하고 싶지 않은 사람이 많다.
- 많은 사람들이 뚜렷한 목표가 없다.

## 카페

### 시사점 및 느낀 점
- 대부분의 사람들이 sns나 포털 서비스를 이용해 카페를 찾으며 이러한 방식에 딱히 불편함을 못느낀다. 그래서 사람들이 특별한 니즈를 못 느끼는 만큼 초기에 유저 모집이 조금 힘들 수 있다고 생각된다(하려면 정말 제대로 만들어야 할 거 같아요). 하지만 다음 설문에서 주기적으로 서비스를 사용할 의향이 60%를 넘긴 많큼 정말 (망고플레이트 같은 ㅎ) 제대로 된 서비스를 만들면 성공 할 수도 있을거 같다.
- 자주 가는곳 혹은 한 곳만 꾸준히 이용하는 사람들이 생각보다 많은데 이런 사람들은 자주 가는 카페의 정보를 이미 알고 있어서 앱을 사용하지 않을 확률이 높은데 이런 유저들이 앱을 사용하도록 유도할 만한 요소도 함께 고민해보면 좋을 것 같다.

### 특기할 만한 포인트
- 1,2,3순위를 합치면 가격과 접근성이 커피 맛 보다 더 높은 수치를 가진다.
- 처음 가는 지역에서 커피를 마실 경우 접근성이 높은 우선순위를 차지한다.
- 데이트, 지인과의 만남에선 커피맛, 인테리어, 편한 의자와 같이 직접적으로 느끼고 만족을 얻을 수 있는(?) 그런 요소들의 수치가 더 높다. (단어가 안떠올라서 뭐라고 설명해야 할 지 모르겠어요)
- 맛집을 찾아주는 어플리케이션 사용 비율은 매우 낮다
- 대부분 기존에 사용하는 경로 탐색 방법에서 불편함을 못 느낀다

## e스포츠

### 시사점 느낀 점
- 요즘 모바일 카트가 핫하던데, 실제 카트  e스포츠 경기를 보는 사람이 있어서 놀라움!
- 좋아하는 팀이 있는 경우에는 많은 관심을 보이지만, 좋아하는 팀이 없을 경우 관심을 크게 보이지 않는거 같아서, 목표 타겟을 명확하게 해야할 것 같다.

### 특기할 만한 포인트
- 대부분의 사람들이 e스포츠 리그 경기 일정 결과에 많은 관심을 두지 않는 것 같다. (절반 이상의 사람이 한달에 1회 혹은 주 1회 미만으로 확인함)
- 기존 서비스에서 불편함을 대부분 느끼지 못함
- 좋아하는 팀이 있을 경우엔 매우 자주 확인함( 하루 1회 이상)
- e스포츠 팀을 추천해주고, 이후 설정한 응원 팀을 위주로 경기 일정과 결과, 뉴스, 영상 등을 모아서 보여주는 어플리케이션을 사용할 의향이 많이 없다😭😭

**Comment by hjoopark** [comment]
### **백수탈출 앱**
**중요 포인트**
- 학생이나 대학생이 가장 많이 응답하였고, 타켓층을 노릴 수 있을 것 같다.
- 핸드폰을 하면서 시간을 보내는 사람들이 많은 것 같았다.
- 운동이나 일찍 일어나기, 약속 등 해야 할 일들을 만들어 내면서 생활을 개선해 나간 것 같다.
- 해야 할 일들을 계획해도 의지만으로 지키지 못하는 경우들이 많은 것 같다.
**시사 점 느낀 점**
- 가장 많은 응답이 있었던 것을 보면 관심도가 가장 많은 것 같았다.
- 늦게 일어나거나 목표가 없는 사람들에겐 운동이나 일찍 일어나기 등 부지런해질 수 있는 것들을 미션으로 주면 좋을 것 같다.
- 자격증, 시험, 공부 등 자신의 목표가 있는 사람들에겐 하루하루 미션이나 보상 형식으로 할 일을 채워 나갈 수 있도록 하면 좋을 것 같다. (d-day를 보이도록 해도 좋을 것 같다.)

### **카페 가격비교 앱**
**중요 포인트**
- 회사주변에서 갈 때나 데이트 할 때 같이 목적에 따라서 카페를 선택하는 기준이 많이 다른 것 같다.
- 이미 인테리어가 괜찮은 카페는 sns에서 찾아서 가고, 비즈니스로 가는 카페는 주변 카페를 가는 것 같다.
**시사 점 느낀 점**
- 응답 결과를 보면서 이미 프랜차이즈 커피점들도 여러 곳에 많이 있어서 앱을 보고 비교를 할까 생각이 들었다.
- 필요한 서비스에서 카페 이벤트 알려주고 쿠폰을 모바일로 모으는 서비스가 추가 된 앱을 생각한다면 괜찮을 것 같다.

### **e스포츠 앱**
**중요 포인트**
- 세 질문지 중에서 가장 응답 수가 적었고, 그 중에서 관심이 있는 사람도 적었다.
- e스포츠 중에서는 lol이 가장 인기가 많았다.
- 경기 확인이나 일정 등에 대한 불편함이 없었다.
**시사 점 느낀 점**
- 나도 야구를 즐겨 보는데 야구 경기 결과나 경기 내용 , 일정에 대한 것들은 네이버 스포츠에서 대부분 확인이 가능하다. 페이지 앱을 깔아보기는 했지만 페이지 앱에서 확인 한 적이 드문 것 같다. ( 앱이 있어도 사용할까 의문이 들었다)
- 네이버 스포츠 앱 웹을 들어가서 확인을 해봤는데 일정이나 순위 등은 정리가 잘 되어 있는 것 같았다. 하지만 팀별로 모아볼 수 있는 부분은 부족한 것 같아서 그 부분을 중점으로 두면 차별점을 가질 수 있을 것 같다.

**Comment by adfilm2** [comment]
### **백수 탈출앱**
**분석**
- 침대에 누워 핸드폰을 사용하는 시간이 가장 나태하다고 느낌
   => 항상 핸드폰을 들고 있기 때문에 앱의 효과가 크게 나타날 수 있다.
-  개선하기 위해 대부분이 어떤 것을 시도해보려는 노력을 함
   => 앱을 사용하기에 충분한 동기
- 게을러지게 된 이유로 뚜렷한 목표나 해야 할 일이 딱히 없고, 늦게 일어났기때문이라는 결과가 높음. 뚜렷한 목표나 해야 할 일이 딱히 없었기 때문에 늦게 일어난 것이 아닌가 하는 추론 가능

**느낀 점**
- 많은 사람들이 '작은 것이라도 뭔가 행동을 해야 한다' 라는 방법 자체는 알고있음.
  그러나 (저도 그렇고) 작심삼일이 되기 일쑤고 자꾸 무력감에 빠지게 되어 극복 하지 못하는 경우도 많기 때문에 어플 알람을 무시하지않고 꾸준히 미션을 수행할만한 직관적인 동기를 제시하는 것이 중요하다고 생각함

---

### **카페 가격비교 앱**
**분석**
1. 업무, 학업상 카페를 찾을 때 가장 먼저 고려하는 요소 (45명응답)
    **접근성**  : 55%(25명)
    **가격**: 20% (9명)
   **편한 의자** : 11%(5명)
   **와이파이**: 4%(2명)
    **커피맛, 인테리어, 디저트맛**: 각 2% (각1명)

2. 지인과의 만남, 데이트 시에 카페를 결정하는 요소 1순위로 (47명응답)
  **인테리어** : 38% (18명)
   **커피 맛**: 23% (11명)
   **편한 의자**: 17% (8명)
   **접근성**: 12% (6명)
   **디저트 맛**: 6% (3명)

**느낀점**
- 목적에 따라 니즈가 뚜렷하게 달라지기때문에 목적을 구분해야 할 필요가 있을 것 같음
- 솔직한 후기 서비스를 원하는 사람들이 많음. 설문조사 항목중 편한 의자/인테리어/디저트맛/커피맛 등은 솔직한 후기로 채워져야 하는 부분이기 때문에  만약 2번을 위한 서비스도 진행할 거라면 오히려 "솔직 후기"를 강점으로 내세우는 것도 좋을 것 같음. 1번을 위한 서비스라면 가격필터링 서비스와 지도서비스 위주면 될듯
---
### **e스포츠**
**분석/ 느낀점**
- 설문 응답자 중 e스포츠를 즐겨관람하지 않는다고 대답한 인원을 빼면 16개의 응답 뿐으로 표본이 부족함
- 대다수의 사람들이 기존 경로에서 불편함을 느끼지 않았다고 대답(14명) => 하지만 자주 사용할 것 같다 9명, 한 번 써보기는 할 것 같다 4명으로 13명이 쓸 의사가 있다고 대답함. 팬심과 관련있는 부분일지도
- 일정이나 스코어를 확인하는데 별 불편함이 없다고 느낀다면 팀별 선수 정보, 인터뷰, 뉴스기사 등에 초점을 두는 것도 나쁘지 않을 것 같다. (팬심 공략)

**Comment by suath** [comment]
**### 백수탈출앱**
**포인트**
- 다들 게으름 근데 또 되게 엄격함 (강한동기부여를 바람)
- 사람들의 반응이 재미있음
**느낀점**
- 약간 다들 자기의 게으름을 고백하고 싶어하는듯.
게으름의 동지애를 부각시키면 좋겠다. ex) 지금 게으른 사람 (오늘의 게을러 100명) 
- 게을러도 괜찮아.. 그래도 오늘은 이거 하나만 해보자! 의 컨셉, ?
기본적으로 사람들은 너무 게을러서 뭐가 미션이 많고 그러면, 그냥 안볼듯
- 다만 빡세게 살고싶은 사람을 위해 가짜사나이 모드를 만들어주자. 


**### 커피앱**
**포인트**
- 불편한점과 개선방안에서 보이는 포인트들이 다양
**시사점**
- 기술적으로 쉽게 해결할 수 있는 부분보다는 현실과의 괴리에서 오는 불편함들이 큼
- 가격비교는 할수있을거 같은데 그 이외의 페인포인트는 해결하기 어렵지 않을까 그래서 
가격비교는 지도앱에서도 어느정도 제공해주는 부분이니, 
다르게 접근하여 콘센트 표기 캠페인이나, 만석알림 시스템을 만들면 좋겠다는 생각이 듬
카페 좌석 예약 시스템 :)?

**### **e스포츠앱**
**포인트**** 
- 매일 경기일정을 확인하는 헤비유저층(예상), 이용하는 타 서비스에 불만없음 
- 개선필요성을 느끼는 부분은 크게 1.팀설정 2.선수설정 3.웹자료(영상,sns)수집 4.알람
**시사점** 
- 큰 불만이 없는 만큼 naver,qwer와 차별화할 수 있도록 컨셉을 잘 잡아야 할듯.

**Comment by junsubenkim** [comment]
투표 결과
**1안 : 백수탈출 앱**
2안 : 카페찾기 앱
3안 : e스포츠 앱

그러나 '2안, 3안으로 최대한 넘어가지 않게 1안 백수탈출 앱을 최대한 만들기'로 결정되었습니다.
